//! Operating system basis drivers module
mod clipboard_clear;
mod clipboard_get;
mod clipboard_set;
mod os_battery_info;
mod os_get_default_browser;
mod os_get_domain;
mod os_get_env;
mod os_get_hostname;
mod os_get_locale;
mod os_get_os_version;
mod os_get_time;
mod os_get_timezone;
mod os_get_uptime;
mod os_get_user;
mod os_hibernate;
mod os_lock;
mod os_logout;
mod os_memory_info;
mod os_notification;
mod os_reboot;
mod os_screen_off;
mod os_screen_on;
mod os_set_env;
mod os_set_time;
mod os_set_timezone;
mod os_shutdown;
mod os_sleep;
mod os_wallpaper_get;
mod os_wallpaper_set;
mod system_info;
pub use clipboard_clear::ClipboardClearDriver;
pub use clipboard_get::ClipboardGetDriver;
pub use clipboard_set::ClipboardSetDriver;
pub use os_battery_info::OsBatteryInfoDriver;
pub use os_get_default_browser::OsGetDefaultBrowserDriver;
pub use os_get_domain::OsGetDomainDriver;
pub use os_get_env::OsGetEnvDriver;
pub use os_get_hostname::OsGetHostnameDriver;
pub use os_get_locale::OsGetLocaleDriver;
pub use os_get_os_version::OsGetOsVersionDriver;
pub use os_get_time::OsGetTimeDriver;
pub use os_get_timezone::OsGetTimezoneDriver;
pub use os_get_uptime::OsGetUptimeDriver;
pub use os_get_user::OsGetUserDriver;
pub use os_hibernate::OsHibernateDriver;
pub use os_lock::OsLockDriver;
pub use os_logout::OsLogoutDriver;
pub use os_memory_info::OsMemoryInfoDriver;
pub use os_notification::OsNotificationDriver;
pub use os_reboot::OsRebootDriver;
pub use os_screen_off::OsScreenOffDriver;
pub use os_screen_on::OsScreenOnDriver;
pub use os_set_env::OsSetEnvDriver;
pub use os_set_time::OsSetTimeDriver;
pub use os_set_timezone::OsSetTimezoneDriver;
pub use os_shutdown::OsShutdownDriver;
pub use os_sleep::OsSleepDriver;
pub use os_wallpaper_get::OsWallpaperGetDriver;
pub use os_wallpaper_set::OsWallpaperSetDriver;
pub use system_info::SystemInfoDriver;
