// display_control/mod.rs
//! Display control skills module

mod common;
mod display_control_list;
mod display_control_primary_get;
mod display_control_resolution_get;
mod display_control_resolution_set;
mod display_control_scale_get;
mod display_control_orientation_get;
mod display_control_orientation_set;
mod display_control_refresh_rate_get;
mod display_control_brightness_get;
mod display_control_brightness_set;

pub use display_control_list::DisplayControlListSkill;
pub use display_control_primary_get::DisplayControlPrimaryGetSkill;
pub use display_control_resolution_get::DisplayControlResolutionGetSkill;
pub use display_control_resolution_set::DisplayControlResolutionSetSkill;
pub use display_control_scale_get::DisplayControlScaleGetSkill;
pub use display_control_orientation_get::DisplayControlOrientationGetSkill;
pub use display_control_orientation_set::DisplayControlOrientationSetSkill;
pub use display_control_refresh_rate_get::DisplayControlRefreshRateGetSkill;
pub use display_control_brightness_get::DisplayControlBrightnessGetSkill;
pub use display_control_brightness_set::DisplayControlBrightnessSetSkill;