//! WiFi control skills module

mod common;
mod wifi_analyze_quality;
mod wifi_auto_connect_toggle;
mod wifi_band_preference_get;
mod wifi_band_preference_set;
mod wifi_connect;
mod wifi_connect_hidden;
mod wifi_disconnect;
mod wifi_dns_set;
mod wifi_export_config;
mod wifi_forget;
mod wifi_get_channel;
mod wifi_get_interface_list;
mod wifi_get_noise_level;
mod wifi_get_saved_passwords;
mod wifi_hotspot_create;
mod wifi_hotspot_stop;
mod wifi_import_config;
mod wifi_list_connections;
mod wifi_mac_address_get;
mod wifi_mac_address_set;
mod wifi_ping_gateway;
mod wifi_priority_set;
mod wifi_proxy_set;
mod wifi_roaming_toggle;
mod wifi_scan;
mod wifi_set_interface_power;
mod wifi_status;
mod wifi_turn_off;
mod wifi_turn_on;
mod wifi_wps_connect;

pub use wifi_analyze_quality::WifiAnalyzeQualitySkill;
pub use wifi_auto_connect_toggle::WifiAutoConnectToggleSkill;
pub use wifi_band_preference_get::WifiBandPreferenceGetSkill;
pub use wifi_band_preference_set::WifiBandPreferenceSetSkill;
pub use wifi_connect::WifiConnectSkill;
pub use wifi_connect_hidden::WifiConnectHiddenSkill;
pub use wifi_disconnect::WifiDisconnectSkill;
pub use wifi_dns_set::WifiDnsSetSkill;
pub use wifi_export_config::WifiExportConfigSkill;
pub use wifi_forget::WifiForgetSkill;
pub use wifi_get_channel::WifiGetChannelSkill;
pub use wifi_get_interface_list::WifiGetInterfaceListSkill;
pub use wifi_get_noise_level::WifiGetNoiseLevelSkill;
pub use wifi_get_saved_passwords::WifiGetSavedPasswordsSkill;
pub use wifi_hotspot_create::WifiHotspotCreateSkill;
pub use wifi_hotspot_stop::WifiHotspotStopSkill;
pub use wifi_import_config::WifiImportConfigSkill;
pub use wifi_list_connections::WifiListConnectionsSkill;
pub use wifi_mac_address_get::WifiMacAddressGetSkill;
pub use wifi_mac_address_set::WifiMacAddressSetSkill;
pub use wifi_ping_gateway::WifiPingGatewaySkill;
pub use wifi_priority_set::WifiPrioritySetSkill;
pub use wifi_proxy_set::WifiProxySetSkill;
pub use wifi_roaming_toggle::WifiRoamingToggleSkill;
pub use wifi_scan::WifiScanSkill;
pub use wifi_set_interface_power::WifiSetInterfacePowerSkill;
pub use wifi_status::WifiStatusSkill;
pub use wifi_turn_off::WifiTurnOffSkill;
pub use wifi_turn_on::WifiTurnOnSkill;
pub use wifi_wps_connect::WifiWpsConnectSkill;
