// application_control/mod.rs
//! Application control skills module

mod common;
mod application_control_launch;
mod application_control_launch_with_args;
mod application_control_launch_as_admin;
mod application_control_close;
mod application_control_is_running;
mod application_control_wait_for_exit;
mod application_control_get_path;
mod application_control_wait_for;
mod application_control_restart;
mod application_control_list_running;
mod application_control_install;
mod application_control_uninstall;

pub use application_control_launch::ApplicationControlLaunchSkill;
pub use application_control_launch_with_args::ApplicationControlLaunchWithArgsSkill;
pub use application_control_launch_as_admin::ApplicationControlLaunchAsAdminSkill;
pub use application_control_close::ApplicationControlCloseSkill;
pub use application_control_is_running::ApplicationControlIsRunningSkill;
pub use application_control_wait_for_exit::ApplicationControlWaitForExitSkill;
pub use application_control_get_path::ApplicationControlGetPathSkill;
pub use application_control_wait_for::ApplicationControlWaitForSkill;
pub use application_control_restart::ApplicationControlRestartSkill;
pub use application_control_list_running::ApplicationControlListRunningSkill;
pub use application_control_install::ApplicationControlInstallSkill;
pub use application_control_uninstall::ApplicationControlUninstallSkill;