//! Window control skills module

mod common;

mod window_control_minimize;
mod window_control_maximize;
mod window_control_restore;
mod window_control_resize;
mod window_control_move;
mod window_control_close;
mod window_control_kill;
mod window_control_bring_to_top;
mod window_control_send_to_back;
mod window_control_set_always_on_top;
mod window_control_get_title;
mod window_control_get_process;
mod window_control_screenshot;
mod window_control_ocr_region;
mod window_control_list;
mod window_control_find;
mod window_control_activate;
mod window_control_get_position;
mod window_control_get_focus;
mod window_control_get_selected;
mod window_control_send_keys;
mod window_control_send_shortcut;
mod window_control_wait_for_focus;

pub use window_control_minimize::WindowControlMinimizeSkill;
pub use window_control_maximize::WindowControlMaximizeSkill;
pub use window_control_restore::WindowControlRestoreSkill;
pub use window_control_resize::WindowControlResizeSkill;
pub use window_control_move::WindowControlMoveSkill;
pub use window_control_close::WindowControlCloseSkill;
pub use window_control_kill::WindowControlKillSkill;
pub use window_control_bring_to_top::WindowControlBringToTopSkill;
pub use window_control_send_to_back::WindowControlSendToBackSkill;
pub use window_control_set_always_on_top::WindowControlSetAlwaysOnTopSkill;
pub use window_control_get_title::WindowControlGetTitleSkill;
pub use window_control_get_process::WindowControlGetProcessSkill;
pub use window_control_screenshot::WindowControlScreenshotSkill;
pub use window_control_ocr_region::WindowControlOcrRegionSkill;
pub use window_control_list::WindowControlListSkill;
pub use window_control_find::WindowControlFindSkill;
pub use window_control_activate::WindowControlActivateSkill;
pub use window_control_get_position::WindowControlGetPositionSkill;
pub use window_control_get_focus::WindowControlGetFocusSkill;
pub use window_control_get_selected::WindowControlGetSelectedSkill;
pub use window_control_send_keys::WindowControlSendKeysSkill;
pub use window_control_send_shortcut::WindowControlSendShortcutSkill;
pub use window_control_wait_for_focus::WindowControlWaitForFocusSkill;